function createNode_1() {
    var e_0 = document.createElement("div");
    e_0.setAttribute("class", "poem aside-card");
    var e_1 = document.createElement("div");
    e_1.setAttribute("class", "top");
    var e_2 = document.createElement("h1");
    e_2.appendChild(document.createTextNode("长安古意"));
    e_1.appendChild(e_2);
    var e_3 = document.createElement("span");
    e_3.appendChild(document.createTextNode("唐·卢照邻"));
    e_1.appendChild(e_3);
    e_0.appendChild(e_1);
    var e_4 = document.createElement("p");
    e_4.appendChild(document.createTextNode("\n长安大道连狭斜，"));
    var e_5 = document.createElement("br");
    e_4.appendChild(e_5);
    e_4.appendChild(document.createTextNode("青牛白马七香车。"));
    var e_6 = document.createElement("br");
    e_4.appendChild(e_6);
    e_4.appendChild(document.createTextNode("\n玉辇纵横过主第，"));
    var e_7 = document.createElement("br");
    e_4.appendChild(e_7);
    e_4.appendChild(document.createTextNode("金鞭络绎向侯家。"));
    var e_8 = document.createElement("br");
    e_4.appendChild(e_8);
    e_4.appendChild(document.createTextNode("\n龙衔宝盖承朝日，"));
    var e_9 = document.createElement("br");
    e_4.appendChild(e_9);
    e_4.appendChild(document.createTextNode("凤吐流苏带晚霞。"));
    var e_10 = document.createElement("br");
    e_4.appendChild(e_10);
    e_4.appendChild(document.createTextNode("\n百尺游丝争绕树，"));
    var e_11 = document.createElement("br");
    e_4.appendChild(e_11);
    e_4.appendChild(document.createTextNode("一群娇鸟共啼花。"));
    var e_12 = document.createElement("br");
    e_4.appendChild(e_12);
    e_4.appendChild(document.createTextNode("\n游蜂戏蝶千门侧，"));
    var e_13 = document.createElement("br");
    e_4.appendChild(e_13);
    e_4.appendChild(document.createTextNode("碧树银台万种色。"));
    var e_14 = document.createElement("br");
    e_4.appendChild(e_14);
    e_4.appendChild(document.createTextNode("\n复道交窗作合欢，"));
    var e_15 = document.createElement("br");
    e_4.appendChild(e_15);
    e_4.appendChild(document.createTextNode("双阙连甍垂凤翼。"));
    var e_16 = document.createElement("br");
    e_4.appendChild(e_16);
    e_4.appendChild(document.createTextNode("\n梁家画阁中天起，"));
    var e_17 = document.createElement("br");
    e_4.appendChild(e_17);
    e_4.appendChild(document.createTextNode("汉帝金茎云外直。"));
    var e_18 = document.createElement("br");
    e_4.appendChild(e_18);
    e_4.appendChild(document.createTextNode("\n楼前相望不相知，"));
    var e_19 = document.createElement("br");
    e_4.appendChild(e_19);
    e_4.appendChild(document.createTextNode("陌上相逢讵相识？"));
    var e_20 = document.createElement("br");
    e_4.appendChild(e_20);
    e_4.appendChild(document.createTextNode("\n借问吹箫向紫烟，"));
    var e_21 = document.createElement("br");
    e_4.appendChild(e_21);
    e_4.appendChild(document.createTextNode("曾经学舞度芳年。"));
    var e_22 = document.createElement("br");
    e_4.appendChild(e_22);
    e_4.appendChild(document.createTextNode("\n得成比目何辞死，"));
    var e_23 = document.createElement("br");
    e_4.appendChild(e_23);
    e_4.appendChild(document.createTextNode("愿作鸳鸯不羡仙。"));
    var e_24 = document.createElement("br");
    e_4.appendChild(e_24);
    e_4.appendChild(document.createTextNode("\n比目鸳鸯真可羡，"));
    var e_25 = document.createElement("br");
    e_4.appendChild(e_25);
    e_4.appendChild(document.createTextNode("双去双来君不见？"));
    var e_26 = document.createElement("br");
    e_4.appendChild(e_26);
    e_4.appendChild(document.createTextNode("\n生憎帐额绣孤鸾，"));
    var e_27 = document.createElement("br");
    e_4.appendChild(e_27);
    e_4.appendChild(document.createTextNode("好取门帘帖双燕。"));
    var e_28 = document.createElement("br");
    e_4.appendChild(e_28);
    e_4.appendChild(document.createTextNode("\n双燕双飞绕画梁，"));
    var e_29 = document.createElement("br");
    e_4.appendChild(e_29);
    e_4.appendChild(document.createTextNode("罗帷翠被郁金香。"));
    var e_30 = document.createElement("br");
    e_4.appendChild(e_30);
    e_4.appendChild(document.createTextNode("\n片片行云着蝉鬓，"));
    var e_31 = document.createElement("br");
    e_4.appendChild(e_31);
    e_4.appendChild(document.createTextNode("纤纤初月上鸦黄。"));
    var e_32 = document.createElement("br");
    e_4.appendChild(e_32);
    e_4.appendChild(document.createTextNode("\n鸦黄粉白车中出，"));
    var e_33 = document.createElement("br");
    e_4.appendChild(e_33);
    e_4.appendChild(document.createTextNode("含娇含态情非一。"));
    var e_34 = document.createElement("br");
    e_4.appendChild(e_34);
    e_4.appendChild(document.createTextNode("\n妖童宝马铁连钱，"));
    var e_35 = document.createElement("br");
    e_4.appendChild(e_35);
    e_4.appendChild(document.createTextNode("娼妇盘龙金屈膝。"));
    var e_36 = document.createElement("br");
    e_4.appendChild(e_36);
    e_4.appendChild(document.createTextNode("\n御史府中乌夜啼，"));
    var e_37 = document.createElement("br");
    e_4.appendChild(e_37);
    e_4.appendChild(document.createTextNode("廷尉门前雀欲栖。"));
    var e_38 = document.createElement("br");
    e_4.appendChild(e_38);
    e_4.appendChild(document.createTextNode("\n隐隐朱城临玉道，"));
    var e_39 = document.createElement("br");
    e_4.appendChild(e_39);
    e_4.appendChild(document.createTextNode("遥遥翠幰没金堤。"));
    var e_40 = document.createElement("br");
    e_4.appendChild(e_40);
    e_4.appendChild(document.createTextNode("\n挟弹飞鹰杜陵北，"));
    var e_41 = document.createElement("br");
    e_4.appendChild(e_41);
    e_4.appendChild(document.createTextNode("探丸借客渭桥西。"));
    var e_42 = document.createElement("br");
    e_4.appendChild(e_42);
    e_4.appendChild(document.createTextNode("\n俱邀侠客芙蓉剑，"));
    var e_43 = document.createElement("br");
    e_4.appendChild(e_43);
    e_4.appendChild(document.createTextNode("共宿娼家桃李蹊。"));
    var e_44 = document.createElement("br");
    e_4.appendChild(e_44);
    e_4.appendChild(document.createTextNode("\n娼家日暮紫罗裙，"));
    var e_45 = document.createElement("br");
    e_4.appendChild(e_45);
    e_4.appendChild(document.createTextNode("清歌一啭口氛氲。"));
    var e_46 = document.createElement("br");
    e_4.appendChild(e_46);
    e_4.appendChild(document.createTextNode("\n北堂夜夜人如月，"));
    var e_47 = document.createElement("br");
    e_4.appendChild(e_47);
    e_4.appendChild(document.createTextNode("南陌朝朝骑似云。"));
    var e_48 = document.createElement("br");
    e_4.appendChild(e_48);
    e_4.appendChild(document.createTextNode("\n南陌北堂连北里，"));
    var e_49 = document.createElement("br");
    e_4.appendChild(e_49);
    e_4.appendChild(document.createTextNode("五剧三条控三市。"));
    var e_50 = document.createElement("br");
    e_4.appendChild(e_50);
    e_4.appendChild(document.createTextNode("\n弱柳青槐拂地垂，"));
    var e_51 = document.createElement("br");
    e_4.appendChild(e_51);
    e_4.appendChild(document.createTextNode("佳气红尘暗天起。"));
    var e_52 = document.createElement("br");
    e_4.appendChild(e_52);
    e_4.appendChild(document.createTextNode("\n汉代金吾千骑来，"));
    var e_53 = document.createElement("br");
    e_4.appendChild(e_53);
    e_4.appendChild(document.createTextNode("翡翠屠苏鹦鹉杯。"));
    var e_54 = document.createElement("br");
    e_4.appendChild(e_54);
    e_4.appendChild(document.createTextNode("\n罗襦宝带为君解，"));
    var e_55 = document.createElement("br");
    e_4.appendChild(e_55);
    e_4.appendChild(document.createTextNode("燕歌赵舞为君开。"));
    var e_56 = document.createElement("br");
    e_4.appendChild(e_56);
    e_4.appendChild(document.createTextNode("\n别有豪华称将相，"));
    var e_57 = document.createElement("br");
    e_4.appendChild(e_57);
    e_4.appendChild(document.createTextNode("转日回天不相让。"));
    var e_58 = document.createElement("br");
    e_4.appendChild(e_58);
    e_4.appendChild(document.createTextNode("\n意气由来排灌夫，"));
    var e_59 = document.createElement("br");
    e_4.appendChild(e_59);
    e_4.appendChild(document.createTextNode("专权判不容萧相。"));
    var e_60 = document.createElement("br");
    e_4.appendChild(e_60);
    e_4.appendChild(document.createTextNode("\n专权意气本豪雄，"));
    var e_61 = document.createElement("br");
    e_4.appendChild(e_61);
    e_4.appendChild(document.createTextNode("青虬紫燕坐春风。"));
    var e_62 = document.createElement("br");
    e_4.appendChild(e_62);
    e_4.appendChild(document.createTextNode("\n自言歌舞长千载，"));
    var e_63 = document.createElement("br");
    e_4.appendChild(e_63);
    e_4.appendChild(document.createTextNode("自谓骄奢凌五公。"));
    var e_64 = document.createElement("br");
    e_4.appendChild(e_64);
    e_4.appendChild(document.createTextNode("\n节物风光不相待，"));
    var e_65 = document.createElement("br");
    e_4.appendChild(e_65);
    e_4.appendChild(document.createTextNode("桑田碧海须臾改。"));
    var e_66 = document.createElement("br");
    e_4.appendChild(e_66);
    e_4.appendChild(document.createTextNode("\n昔时金阶白玉堂，"));
    var e_67 = document.createElement("br");
    e_4.appendChild(e_67);
    e_4.appendChild(document.createTextNode("即今惟见青松在。"));
    var e_68 = document.createElement("br");
    e_4.appendChild(e_68);
    e_4.appendChild(document.createTextNode("\n寂寂寥寥扬子居，"));
    var e_69 = document.createElement("br");
    e_4.appendChild(e_69);
    e_4.appendChild(document.createTextNode("年年岁岁一床书。"));
    var e_70 = document.createElement("br");
    e_4.appendChild(e_70);
    e_4.appendChild(document.createTextNode("\n独有南山桂花发，"));
    var e_71 = document.createElement("br");
    e_4.appendChild(e_71);
    e_4.appendChild(document.createTextNode("飞来飞去袭人裾。"));
    var e_72 = document.createElement("br");
    e_4.appendChild(e_72);
    e_0.appendChild(e_4);
    return e_0;
}

function createNode_2() {
    var e_0 = document.createElement("div");
    e_0.setAttribute("class", "poem aside-card");
    var e_1 = document.createElement("div");
    e_1.setAttribute("class", "top");
    var e_2 = document.createElement("h1");
    e_2.appendChild(document.createTextNode("春江花月夜"));
    e_1.appendChild(e_2);
    var e_3 = document.createElement("span");
    e_3.appendChild(document.createTextNode("唐·张若虚"));
    e_1.appendChild(e_3);
    e_0.appendChild(e_1);
    var e_4 = document.createElement("p");
    e_4.appendChild(document.createTextNode("\n春江潮水连海平，"));
    var e_5 = document.createElement("br");
    e_4.appendChild(e_5);
    e_4.appendChild(document.createTextNode("海上明月共潮生。"));
    var e_6 = document.createElement("br");
    e_4.appendChild(e_6);
    e_4.appendChild(document.createTextNode("\n滟滟随波千万里，"));
    var e_7 = document.createElement("br");
    e_4.appendChild(e_7);
    e_4.appendChild(document.createTextNode("何处春江无月明！"));
    var e_8 = document.createElement("br");
    e_4.appendChild(e_8);
    e_4.appendChild(document.createTextNode("\n江流宛转绕芳甸，"));
    var e_9 = document.createElement("br");
    e_4.appendChild(e_9);
    e_4.appendChild(document.createTextNode("月照花林皆似霰。"));
    var e_10 = document.createElement("br");
    e_4.appendChild(e_10);
    e_4.appendChild(document.createTextNode("\n空里流霜不觉飞，"));
    var e_11 = document.createElement("br");
    e_4.appendChild(e_11);
    e_4.appendChild(document.createTextNode("汀上白沙看不见。"));
    var e_12 = document.createElement("br");
    e_4.appendChild(e_12);
    e_4.appendChild(document.createTextNode("\n江天一色无纤尘，"));
    var e_13 = document.createElement("br");
    e_4.appendChild(e_13);
    e_4.appendChild(document.createTextNode("皎皎空中孤月轮。"));
    var e_14 = document.createElement("br");
    e_4.appendChild(e_14);
    e_4.appendChild(document.createTextNode("\n江畔何人初见月？"));
    var e_15 = document.createElement("br");
    e_4.appendChild(e_15);
    e_4.appendChild(document.createTextNode("江月何年初照人？"));
    var e_16 = document.createElement("br");
    e_4.appendChild(e_16);
    e_4.appendChild(document.createTextNode("\n人生代代无穷已，"));
    var e_17 = document.createElement("br");
    e_4.appendChild(e_17);
    e_4.appendChild(document.createTextNode("江月年年望相似。"));
    var e_18 = document.createElement("br");
    e_4.appendChild(e_18);
    e_4.appendChild(document.createTextNode("\n不知江月待何人，"));
    var e_19 = document.createElement("br");
    e_4.appendChild(e_19);
    e_4.appendChild(document.createTextNode("但见长江送流水。"));
    var e_20 = document.createElement("br");
    e_4.appendChild(e_20);
    e_4.appendChild(document.createTextNode("\n白云一片去悠悠，"));
    var e_21 = document.createElement("br");
    e_4.appendChild(e_21);
    e_4.appendChild(document.createTextNode("青枫浦上不胜愁。"));
    var e_22 = document.createElement("br");
    e_4.appendChild(e_22);
    e_4.appendChild(document.createTextNode("\n谁家今夜扁舟子？"));
    var e_23 = document.createElement("br");
    e_4.appendChild(e_23);
    e_4.appendChild(document.createTextNode("何处相思明月楼？"));
    var e_24 = document.createElement("br");
    e_4.appendChild(e_24);
    e_4.appendChild(document.createTextNode("\n可怜楼上月裴回，"));
    var e_25 = document.createElement("br");
    e_4.appendChild(e_25);
    e_4.appendChild(document.createTextNode("应照离人妆镜台。"));
    var e_26 = document.createElement("br");
    e_4.appendChild(e_26);
    e_4.appendChild(document.createTextNode("\n玉户帘中卷不去，"));
    var e_27 = document.createElement("br");
    e_4.appendChild(e_27);
    e_4.appendChild(document.createTextNode("捣衣砧上拂还来。"));
    var e_28 = document.createElement("br");
    e_4.appendChild(e_28);
    e_4.appendChild(document.createTextNode("\n此时相望不相闻，"));
    var e_29 = document.createElement("br");
    e_4.appendChild(e_29);
    e_4.appendChild(document.createTextNode("愿逐月华流照君。"));
    var e_30 = document.createElement("br");
    e_4.appendChild(e_30);
    e_4.appendChild(document.createTextNode("\n鸿雁长飞光不度，"));
    var e_31 = document.createElement("br");
    e_4.appendChild(e_31);
    e_4.appendChild(document.createTextNode("鱼龙潜跃水成文。"));
    var e_32 = document.createElement("br");
    e_4.appendChild(e_32);
    e_4.appendChild(document.createTextNode("\n昨夜闲潭梦落花，"));
    var e_33 = document.createElement("br");
    e_4.appendChild(e_33);
    e_4.appendChild(document.createTextNode("可怜春半不还家。"));
    var e_34 = document.createElement("br");
    e_4.appendChild(e_34);
    e_4.appendChild(document.createTextNode("\n江水流春去欲尽，"));
    var e_35 = document.createElement("br");
    e_4.appendChild(e_35);
    e_4.appendChild(document.createTextNode("江潭落月复西斜。"));
    var e_36 = document.createElement("br");
    e_4.appendChild(e_36);
    e_4.appendChild(document.createTextNode("\n斜月沉沉藏海雾，"));
    var e_37 = document.createElement("br");
    e_4.appendChild(e_37);
    e_4.appendChild(document.createTextNode("碣石潇湘无限路。"));
    var e_38 = document.createElement("br");
    e_4.appendChild(e_38);
    e_4.appendChild(document.createTextNode("\n不知乘月几人归，"));
    var e_39 = document.createElement("br");
    e_4.appendChild(e_39);
    e_4.appendChild(document.createTextNode("落月摇情满江树。"));
    var e_40 = document.createElement("br");
    e_4.appendChild(e_40);
    e_0.appendChild(e_4);
    return e_0;
}

function createNode_3() {
    var e_0 = document.createElement("div");
    e_0.setAttribute("class", "poem aside-card");
    var e_1 = document.createElement("div");
    e_1.setAttribute("class", "top");
    var e_2 = document.createElement("h1");
    e_2.appendChild(document.createTextNode("音乐"));
    e_1.appendChild(e_2);
    var e_3 = document.createElement("div");
    const ap = new APlayer({
        container: e_3,
        audio: [{
            name: '梦之津渡',
            artist: '啃书',
            url: '/musics/梦之津渡.mp3',
            cover: '/musics/梦之津渡.jpg'
        }]
    });
    e_0.appendChild(e_3);
    return e_0;
}

$(document).ready(function() {
    document.querySelector(".aside-top").appendChild(createNode_1());
    document.querySelector(".aside-bottom").appendChild(createNode_2());
    var parentElement = document.querySelector(".aside-bottom");
    var firstChild = parentElement.firstChild;
    parentElement.insertBefore(createNode_3(), firstChild);
});